import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
import { GoogleGenAI } from '@google/genai';
import dotenv from 'dotenv';
import { createServer as createViteServer } from 'vite';
import {
  evaluateComprehension,
  benchmarkTestCases,
  ComprehensionRequest
} from './server/comprehensionEngine';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = 3000;

app.use(express.json({ limit: '25mb' }));

// In-memory sessions store (mirrors Firestore collection for demo & persistence)
const sessionsStore: Record<string, any> = {};

// Lazy initialization for Gemini client
let geminiClient: GoogleGenAI | null = null;
function getGemini(): GoogleGenAI | null {
  if (!geminiClient && process.env.GEMINI_API_KEY) {
    geminiClient = new GoogleGenAI({
      apiKey: process.env.GEMINI_API_KEY,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build'
        }
      }
    });
  }
  return geminiClient;
}

// Health endpoint
app.get('/api/health', (req, res) => {
  res.json({
    status: 'ok',
    geminiConfigured: Boolean(process.env.GEMINI_API_KEY),
    timestamp: new Date().toISOString()
  });
});

// Transcribe Audio Endpoint (Gemini gemini-3.5-transcribe)
app.post('/api/transcribe-audio', async (req, res) => {
  try {
    const { audioBase64, mimeType = 'audio/webm', language = 'hi' } = req.body;

    if (!audioBase64) {
      return res.status(400).json({ error: 'Audio data is required' });
    }

    const ai = getGemini();

    if (!ai) {
      return res.status(503).json({
        error: 'Gemini API not configured on server',
        fallback: true,
        transcript: ''
      });
    }

    // Clean base64 header if present (e.g. data:audio/webm;base64,...)
    const cleanBase64 = audioBase64.replace(/^data:[^;]+;base64,/, '');

    const audioPart = {
      inlineData: {
        mimeType: mimeType.includes('mp4') ? 'audio/mp4' : mimeType.includes('wav') ? 'audio/wav' : 'audio/webm',
        data: cleanBase64
      }
    };

    const promptText = `Transcribe the borrower's spoken response accurately.
The borrower may speak in Hindi, Indian English, or mixed Hinglish.
Do NOT translate the response. Transcribe verbatim in the language spoken (Devanagari for Hindi words, Roman script for Hinglish/English).
Output ONLY the transcription without prefixes or conversational commentary.`;

    const response = await ai.models.generateContent({
      model: 'gemini-3.5-transcribe',
      contents: {
        parts: [
          audioPart,
          { text: promptText }
        ]
      }
    });

    const transcript = (response.text || '').trim();

    res.json({
      transcript,
      confidence: transcript.length > 5 ? 'high' : 'medium',
      language
    });
  } catch (error: any) {
    console.error('Audio transcription error:', error);
    res.status(500).json({
      error: error.message || 'Failed to transcribe audio',
      fallback: true
    });
  }
});

// Synthesize Speech Endpoint (Gemini gemini-3.1-flash-tts-preview)
app.post('/api/synthesize-speech', async (req, res) => {
  try {
    const { text, language = 'en' } = req.body;

    if (!text) {
      return res.status(400).json({ error: 'Text is required for speech synthesis' });
    }

    const ai = getGemini();

    if (!ai) {
      return res.status(503).json({
        error: 'Gemini TTS unavailable, fallback to browser synthesis',
        fallback: true
      });
    }

    const voiceName = language === 'hi' ? 'Kore' : 'Puck';
    const cleanText = text.replace(/[*_#`]/g, '').trim();

    const response = await ai.models.generateContent({
      model: 'gemini-3.1-flash-tts-preview',
      contents: [{
        parts: [{
          text: `Read in a warm, patient, clear, and reassuring tone for a first-time borrower: ${cleanText}`
        }]
      }],
      config: {
        responseModalities: ['AUDIO'],
        speechConfig: {
          voiceConfig: {
            prebuiltVoiceConfig: { voiceName }
          }
        }
      }
    });

    const base64Audio = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;

    if (base64Audio) {
      res.json({
        audioBase64: base64Audio,
        mimeType: 'audio/wav',
        voice: voiceName
      });
    } else {
      res.status(500).json({
        error: 'No audio generated by TTS model',
        fallback: true
      });
    }
  } catch (err: any) {
    console.warn('Gemini TTS notice, falling back to browser speech:', err?.message);
    res.status(500).json({
      error: err.message || 'TTS generation failed',
      fallback: true
    });
  }
});

// Evaluate Borrower Comprehension Endpoint (Gemini gemini-3.7-flash + Rule Engine)
app.post('/api/evaluate-comprehension', async (req, res) => {
  try {
    const { questionId, concept, userTranscript, language = 'en', offerFacts, attemptCount = 1 } = req.body;

    if (!userTranscript || typeof userTranscript !== 'string') {
      return res.status(400).json({ error: 'Valid user transcript is required' });
    }

    const ai = getGemini();
    const evaluation = await evaluateComprehension(ai, {
      questionId,
      concept: concept || questionId,
      userTranscript: userTranscript.trim(),
      language: language as 'en' | 'hi',
      offerFacts,
      attemptCount: Number(attemptCount) || 1
    });

    res.json(evaluation);
  } catch (error: any) {
    console.error('Comprehension evaluation error:', error);
    res.status(500).json({
      error: error.message || 'Failed to evaluate comprehension',
      status: 'unable_to_assess',
      evidence: 'Server evaluation temporary glitch.'
    });
  }
});

// Automated Comprehension Benchmark Test Suite Runner
app.get('/api/test-comprehension', async (req, res) => {
  try {
    const ai = getGemini();
    const mockOfferFacts = {
      lenderName: 'Demo Lending Platform (NBFC Partner: ABC Finance Ltd)',
      sanctionedAmountPaise: 1000000,
      upfrontFeePaise: 50000,
      netDisbursementPaise: 950000,
      totalScheduledRepaymentPaise: 1120000,
      instalments: [
        { instalmentNumber: 1, dueDate: '30/09/2026', amountPaise: 560000 },
        { instalmentNumber: 2, dueDate: '30/10/2026', amountPaise: 560000 }
      ]
    };

    const results = [];

    for (const testCase of benchmarkTestCases) {
      const startTime = Date.now();
      const evaluation = await evaluateComprehension(ai, {
        questionId: testCase.questionId,
        concept: testCase.concept,
        userTranscript: testCase.inputTranscript,
        language: testCase.language,
        offerFacts: mockOfferFacts,
        attemptCount: 1
      });
      const latencyMs = Date.now() - startTime;

      const passed = evaluation.status === testCase.expectedStatus;

      results.push({
        testId: testCase.id,
        name: testCase.name,
        category: testCase.category,
        inputTranscript: testCase.inputTranscript,
        expectedStatus: testCase.expectedStatus,
        actualStatus: evaluation.status,
        passed,
        latencyMs,
        evidence: evaluation.evidence,
        identifiedMismatch: evaluation.identifiedMismatch
      });
    }

    const passedCount = results.filter(r => r.passed).length;
    const totalCount = results.length;

    res.json({
      summary: {
        total: totalCount,
        passed: passedCount,
        failed: totalCount - passedCount,
        passRate: `${Math.round((passedCount / totalCount) * 100)}%`,
        evaluatedWith: ai ? 'gemini-3.7-flash + deterministic_rules' : 'deterministic_rules_fallback'
      },
      results
    });
  } catch (error: any) {
    console.error('Test runner error:', error);
    res.status(500).json({ error: error.message });
  }
});

// Extract KFS Endpoint
app.post('/api/extract-kfs', async (req, res) => {
  try {
    const { documentText, sampleKey, reviewerEmail } = req.body;

    if (!documentText) {
      return res.status(400).json({ error: 'Document text is required for extraction' });
    }

    const ai = getGemini();

    let extractedData: any = null;

    if (ai) {
      try {
        const prompt = `You are a compliance assistant under the Reserve Bank of India (RBI) Digital Lending Guidelines.
Extract the structured Key Fact Statement (KFS) from the following loan document.
Return a STRICT JSON object with these EXACT keys (all monetary amounts MUST be positive integers in Indian paise, where ₹1 = 100 paise):

{
  "lenderName": string,
  "sanctionedAmountPaise": integer (e.g. 1000000 for ₹10,000),
  "upfrontFeePaise": integer (e.g. 50000 for ₹500),
  "netDisbursementPaise": integer (sanctioned minus upfront fee, e.g. 950000 for ₹9,500),
  "totalScheduledRepaymentPaise": integer (e.g. 1120000 for ₹11,200),
  "interestRateDisclosed": string (e.g. "18.0% p.a. reducing balance"),
  "aprDisclosed": string (e.g. "28.4% p.a. (pending verified calculation)"),
  "coolingOffDays": integer (e.g. 3),
  "coolingOffDetails": string,
  "latePaymentTerms": string,
  "dailyLateFeePaise": integer (e.g. 5000 for ₹50),
  "gracePeriodDays": integer (e.g. 3),
  "autoDebitTerms": string,
  "bounceChargePaise": integer (e.g. 15000 for ₹150),
  "instalments": [
    {
      "instalmentNumber": 1,
      "dueDate": "30/09/2026",
      "amountPaise": 560000,
      "principalPartPaise": 485000,
      "interestPartPaise": 75000
    }
  ],
  "complaintOfficer": {
    "name": string,
    "designation": string,
    "email": string,
    "phone": string,
    "ombudsmanPortal": "https://cms.rbi.org.in"
  },
  "excerpts": [
    {
      "field": string,
      "page": integer,
      "text": string
    }
  ]
}

Document Text to extract from:
${documentText}`;

        const response = await ai.models.generateContent({
          model: 'gemini-3.7-flash',
          contents: prompt,
          config: {
            responseMimeType: 'application/json'
          }
        });

        if (response.text) {
          extractedData = JSON.parse(response.text);
        }
      } catch (geminiErr) {
        console.warn('Gemini extraction notice, falling back to structured parser:', geminiErr);
      }
    }

    // If Gemini not configured or parsing required fallback:
    if (!extractedData) {
      // Deterministic fallback based on document text inspection
      const isConflict = documentText.includes('CONFLICT') || sampleKey === 'kfs003';
      const isRevised = documentText.includes('3 instalments') || sampleKey === 'kfs002';

      if (isConflict) {
        extractedData = {
          id: 'offer-kfs-003-conflict',
          lenderName: 'Demo Lending Platform (NBFC Partner: ABC Finance Ltd)',
          sanctionedAmountPaise: 1000000, // ₹10,000
          upfrontFeePaise: 50000, // ₹500
          netDisbursementPaise: 950000, // ₹9,500
          totalScheduledRepaymentPaise: 1150000, // ₹11,500 (Conflicting!)
          interestRateDisclosed: '18.0% p.a. reducing balance',
          aprDisclosed: '24.0% p.a. (CONFLICT: Schedule implies higher)',
          coolingOffDays: 3,
          coolingOffDetails: 'Borrower can exit within 3 days without penalty by repaying principal + proportionate interest.',
          coolingOffDetailsHi: 'उधारकर्ता 3 दिन की कूलिंग-ऑफ अवधि में बिना किसी जुर्माने के लोन वापस कर सकता है।',
          latePaymentTerms: 'Late fee of ₹50/day after 3 days grace period (capped at ₹250 max).',
          latePaymentTermsHi: '3 दिन की छूट के बाद ₹50 प्रतिदिन विलंब शुल्क (अधिकतम ₹250)।',
          dailyLateFeePaise: 5000,
          gracePeriodDays: 3,
          autoDebitTerms: 'e-NACH auto-debit on due date between 6:00 AM - 10:00 AM. NACH bounce charge ₹150.',
          autoDebitTermsHi: 'देय तिथि पर e-NACH ऑटो-डेबिट। बाउंस होने पर ₹150 शुल्क।',
          bounceChargePaise: 15000,
          instalments: [
            { instalmentNumber: 1, dueDate: '30/09/2026', amountPaise: 560000, principalPartPaise: 485000, interestPartPaise: 75000 },
            { instalmentNumber: 2, dueDate: '30/10/2026', amountPaise: 590000, principalPartPaise: 515000, interestPartPaise: 75000 }
          ],
          dataPermissions: [
            { id: 'p1', name: 'SMS (Financial only)', nameHi: 'एसएमएस (केवल वित्तीय)', purpose: 'Used exclusively to verify bank balance alerts and fraud protection.', purposeHi: 'केवल बैंक अलर्ट और धोखाधड़ी रोकथाम के लिए।', isMandatory: true },
            { id: 'p2', name: 'Approximate Location', nameHi: 'अनुमानित स्थान', purpose: 'To comply with state jurisdiction lending regulations.', purposeHi: 'राज्य क्षेत्राधिकार नियमों के अनुपालन हेतु।', isMandatory: true },
            { id: 'p3', name: 'Contact Book Access', nameHi: 'संपर्क सूची (कॉन्टैक्ट्स)', purpose: 'Explicitly prohibited under RBI Digital Lending Norms.', purposeHi: 'आरबीआई द्वारा पूर्णतः प्रतिबंधित।', isMandatory: false }
          ],
          complaintOfficer: {
            name: 'Ms. Sunita Sharma',
            designation: 'Principal Nodal Grievance Officer',
            email: 'nodal.officer@demolender.in',
            phone: '+91 1800-209-4357',
            ombudsmanPortal: 'https://cms.rbi.org.in'
          },
          validationStatus: 'needs_review',
          validationNotes: [
            'CRITICAL ARITHMETIC DISCREPANCY: Instalments sum to ₹11,500 but loan summary states ₹11,200.',
            'Requires lender compliance rectification before borrower presentation.'
          ],
          excerpts: [
            { field: 'Sanctioned Amount', page: 1, text: 'Sanctioned Loan Amount: INR 10,000.00' },
            { field: 'Upfront Fee', page: 1, text: 'Upfront Processing Fee: INR 500.00' },
            { field: 'Instalment 2', page: 2, text: 'Instalment 2 Amount: INR 5,900.00' }
          ]
        };
      } else if (isRevised) {
        extractedData = {
          id: 'offer-kfs-002',
          lenderName: 'Demo Lending Platform (NBFC Partner: ABC Finance Ltd)',
          sanctionedAmountPaise: 1500000, // ₹15,000
          upfrontFeePaise: 75000, // ₹750
          netDisbursementPaise: 1425000, // ₹14,250
          totalScheduledRepaymentPaise: 1680000, // ₹16,800 (3 x 5600)
          interestRateDisclosed: '18.0% p.a. reducing balance',
          aprDisclosed: '26.8% p.a. (pending verified calculation)',
          coolingOffDays: 3,
          coolingOffDetails: 'Borrower can exit within 3 days without penalty by repaying principal + proportionate interest.',
          coolingOffDetailsHi: 'उधारकर्ता 3 दिन की कूलिंग-ऑफ अवधि में बिना किसी जुर्माने के लोन वापस कर सकता है।',
          latePaymentTerms: 'Late fee of ₹50/day after 3 days grace period (capped at ₹250 max).',
          latePaymentTermsHi: '3 दिन की छूट के बाद ₹50 प्रतिदिन विलंब शुल्क (अधिकतम ₹250)।',
          dailyLateFeePaise: 5000,
          gracePeriodDays: 3,
          autoDebitTerms: 'e-NACH auto-debit on due date between 6:00 AM - 10:00 AM. NACH bounce charge ₹150.',
          autoDebitTermsHi: 'देय तिथि पर e-NACH ऑटो-डेबिट। बाउंस होने पर ₹150 शुल्क।',
          bounceChargePaise: 15000,
          instalments: [
            { instalmentNumber: 1, dueDate: '30/09/2026', amountPaise: 560000, principalPartPaise: 485000, interestPartPaise: 75000 },
            { instalmentNumber: 2, dueDate: '30/10/2026', amountPaise: 560000, principalPartPaise: 500000, interestPartPaise: 60000 },
            { instalmentNumber: 3, dueDate: '30/11/2026', amountPaise: 560000, principalPartPaise: 515000, interestPartPaise: 45000 }
          ],
          dataPermissions: [
            { id: 'p1', name: 'SMS (Financial only)', nameHi: 'एसएमएस (केवल वित्तीय)', purpose: 'Used exclusively to verify bank balance alerts and fraud protection.', purposeHi: 'केवल बैंक अलर्ट और धोखाधड़ी रोकथाम के लिए।', isMandatory: true },
            { id: 'p2', name: 'Approximate Location', nameHi: 'अनुमानित स्थान', purpose: 'To comply with state jurisdiction lending regulations.', purposeHi: 'राज्य क्षेत्राधिकार नियमों के अनुपालन हेतु।', isMandatory: true },
            { id: 'p3', name: 'Contact Book Access', nameHi: 'संपर्क सूची (कॉन्टैक्ट्स)', purpose: 'Explicitly prohibited under RBI Digital Lending Norms.', purposeHi: 'आरबीआई द्वारा पूर्णतः प्रतिबंधित।', isMandatory: false }
          ],
          complaintOfficer: {
            name: 'Ms. Sunita Sharma',
            designation: 'Principal Nodal Grievance Officer',
            email: 'nodal.officer@demolender.in',
            phone: '+91 1800-209-4357',
            ombudsmanPortal: 'https://cms.rbi.org.in'
          },
          validationStatus: 'verified',
          validationNotes: ['All arithmetic checks passed: ₹15,000 - ₹750 = ₹14,250 net; 3 x ₹5,600 = ₹16,800 repayment.'],
          excerpts: [
            { field: 'Sanctioned Amount', page: 1, text: 'Sanctioned Loan Amount: INR 15,000.00' },
            { field: 'Upfront Fee', page: 1, text: 'Upfront Processing Fee: INR 750.00' },
            { field: 'Net Payout', page: 1, text: 'Net Disbursed Amount: INR 14,250.00' }
          ]
        };
      } else {
        extractedData = {
          id: 'offer-kfs-001',
          lenderName: 'Demo Lending Platform (NBFC Partner: ABC Finance Ltd)',
          sanctionedAmountPaise: 1000000, // ₹10,000
          upfrontFeePaise: 50000, // ₹500
          netDisbursementPaise: 950000, // ₹9,500
          totalScheduledRepaymentPaise: 1120000, // ₹11,200
          interestRateDisclosed: '18.0% p.a. reducing balance',
          aprDisclosed: '28.4% p.a. (pending verified calculation)',
          coolingOffDays: 3,
          coolingOffDetails: 'Borrower can exit within 3 days without penalty by repaying principal + proportionate interest for the 3 days.',
          coolingOffDetailsHi: 'उधारकर्ता 3 दिन की कूलिंग-ऑफ अवधि में बिना किसी जुर्माने के लोन वापस कर सकता है।',
          latePaymentTerms: 'Late fee of ₹50/day after 3 days grace period (capped at ₹250 max).',
          latePaymentTermsHi: '3 दिन की छूट के बाद ₹50 प्रतिदिन विलंब शुल्क (अधिकतम ₹250)।',
          dailyLateFeePaise: 5000,
          gracePeriodDays: 3,
          autoDebitTerms: 'e-NACH auto-debit on due date between 6:00 AM - 10:00 AM. NACH bounce charge ₹150.',
          autoDebitTermsHi: 'देय तिथि पर e-NACH ऑटो-डेबिट। बाउंस होने पर ₹150 शुल्क।',
          bounceChargePaise: 15000,
          instalments: [
            { instalmentNumber: 1, dueDate: '30/09/2026', amountPaise: 560000, principalPartPaise: 485000, interestPartPaise: 75000 },
            { instalmentNumber: 2, dueDate: '30/10/2026', amountPaise: 560000, principalPartPaise: 515000, interestPartPaise: 45000 }
          ],
          dataPermissions: [
            { id: 'p1', name: 'SMS (Financial only)', nameHi: 'एसएमएस (केवल वित्तीय)', purpose: 'Used exclusively to verify bank balance alerts and fraud protection.', purposeHi: 'केवल बैंक अलर्ट और धोखाधड़ी रोकथाम के लिए।', isMandatory: true },
            { id: 'p2', name: 'Approximate Location', nameHi: 'अनुमानित स्थान', purpose: 'To comply with state jurisdiction lending regulations.', purposeHi: 'राज्य क्षेत्राधिकार नियमों के अनुपालन हेतु।', isMandatory: true },
            { id: 'p3', name: 'Contact Book Access', nameHi: 'संपर्क सूची (कॉन्टैक्ट्स)', purpose: 'Explicitly prohibited under RBI Digital Lending Norms.', purposeHi: 'आरबीआई द्वारा पूर्णतः प्रतिबंधित।', isMandatory: false }
          ],
          complaintOfficer: {
            name: 'Ms. Sunita Sharma',
            designation: 'Principal Nodal Grievance Officer',
            email: 'nodal.officer@demolender.in',
            phone: '+91 1800-209-4357',
            ombudsmanPortal: 'https://cms.rbi.org.in'
          },
          validationStatus: 'verified',
          validationNotes: [
            'All integer paise calculations passed: ₹10,000 - ₹500 = ₹9,500 net; 2 x ₹5,600 = ₹11,200 total scheduled repayment.'
          ],
          excerpts: [
            { field: 'Sanctioned Amount', page: 1, text: 'Sanctioned Loan Amount: INR 10,000.00' },
            { field: 'Upfront Fee', page: 1, text: 'Upfront Processing Fee: INR 500.00' },
            { field: 'Net Payout', page: 1, text: 'Net Disbursed Amount: INR 9,500.00' },
            { field: 'Instalment 1', page: 1, text: 'Instalment 1 Amount: INR 5,600.00 Due 30/09/2026' },
            { field: 'Instalment 2', page: 1, text: 'Instalment 2 Amount: INR 5,600.00 Due 30/10/2026' }
          ]
        };
      }
    }

    // Perform strict code-based arithmetic verification
    const expectedNet = extractedData.sanctionedAmountPaise - extractedData.upfrontFeePaise;
    const netMatches = (expectedNet === extractedData.netDisbursementPaise);

    const sumInstalments = (extractedData.instalments || []).reduce((acc: number, i: any) => acc + (i.amountPaise || 0), 0);
    const repaymentMatches = (sumInstalments === extractedData.totalScheduledRepaymentPaise);

    const passed = netMatches && repaymentMatches;

    const arithmeticNotes: string[] = [];
    if (netMatches) {
      arithmeticNotes.push(`✓ Net disbursement matches: ${extractedData.sanctionedAmountPaise / 100} - ${extractedData.upfrontFeePaise / 100} = ${extractedData.netDisbursementPaise / 100}`);
    } else {
      arithmeticNotes.push(`✕ Net disbursement mismatch: expected ${expectedNet / 100} but document states ${extractedData.netDisbursementPaise / 100}`);
    }

    if (repaymentMatches) {
      arithmeticNotes.push(`✓ Total scheduled repayment matches sum of ${extractedData.instalments?.length} instalments: ₹${extractedData.totalScheduledRepaymentPaise / 100}`);
    } else {
      arithmeticNotes.push(`✕ Scheduled repayment mismatch: sum of instalments is ₹${sumInstalments / 100} but stated total is ₹${extractedData.totalScheduledRepaymentPaise / 100}`);
    }

    res.json({
      facts: extractedData,
      rawExtraction: {
        method: ai ? 'gemini-2.5-flash' : 'deterministic_parser_fallback',
        reviewer: reviewerEmail || 'rs2631298@gmail.com'
      },
      arithmeticCheck: {
        passed,
        netMatches,
        repaymentMatches,
        calculatedNetPaise: expectedNet,
        calculatedRepaymentPaise: sumInstalments,
        notes: arithmeticNotes
      },
      extractionWarnings: !passed ? ['Arithmetic check flagged a discrepancy in the document facts.'] : []
    });
  } catch (error: any) {
    console.error('Extraction error:', error);
    res.status(500).json({ error: error.message || 'Failed to extract KFS facts' });
  }
});

// Save Borrower Session API
app.post('/api/sessions', (req, res) => {
  try {
    const session = req.body;
    if (!session || !session.sessionId) {
      return res.status(400).json({ error: 'Valid session and sessionId are required' });
    }

    sessionsStore[session.sessionId] = {
      ...session,
      updatedAt: new Date().toISOString()
    };

    res.json({ success: true, sessionId: session.sessionId });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// Resume Borrower Session API
app.get('/api/sessions/:id', (req, res) => {
  const { id } = req.params;
  const session = sessionsStore[id];

  if (!session) {
    return res.status(404).json({ error: 'Session not found' });
  }

  res.json(session);
});

// Delete Borrower Session API
app.delete('/api/sessions/:id', (req, res) => {
  const { id } = req.params;
  if (sessionsStore[id]) {
    delete sessionsStore[id];
  }
  res.json({ success: true, message: `Session ${id} removed` });
});

// Assistance Requests Store & API
const assistanceRequestsStore: any[] = [];

app.post('/api/assistance-requests', (req, res) => {
  try {
    const requestData = req.body;
    if (!requestData || !requestData.id) {
      return res.status(400).json({ error: 'Valid assistance request payload is required' });
    }
    assistanceRequestsStore.push({
      ...requestData,
      receivedAt: new Date().toISOString()
    });
    res.json({ success: true, request: requestData });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/assistance-requests', (req, res) => {
  res.json({
    total: assistanceRequestsStore.length,
    requests: assistanceRequestsStore
  });
});

// Verify Final Terms Comparison Endpoint
app.post('/api/verify-final-terms', (req, res) => {
  try {
    const { explainedFacts, proposedFacts, sessionId, clientAcknowledgedChanges } = req.body;

    if (!explainedFacts || !proposedFacts) {
      return res.status(400).json({
        error: 'Both explainedFacts and proposedFacts are required for comparison',
        isMatch: false,
        isUnparseable: true
      });
    }

    // Check numerical differences
    const sanctionedMatches = explainedFacts.sanctionedAmountPaise === proposedFacts.sanctionedAmountPaise;
    const upfrontMatches = explainedFacts.upfrontFeePaise === proposedFacts.upfrontFeePaise;
    const netMatches = explainedFacts.netDisbursementPaise === proposedFacts.netDisbursementPaise;
    const repaymentMatches = explainedFacts.totalScheduledRepaymentPaise === proposedFacts.totalScheduledRepaymentPaise;
    const lenderMatches = (explainedFacts.lenderName || '').trim().toLowerCase() === (proposedFacts.lenderName || '').trim().toLowerCase();

    const isMatch = sanctionedMatches && upfrontMatches && netMatches && repaymentMatches && lenderMatches;
    const repaymentDiffPaise = proposedFacts.totalScheduledRepaymentPaise - explainedFacts.totalScheduledRepaymentPaise;

    // If there is a material change and client did NOT explicitly re-acknowledge
    if (!isMatch && !clientAcknowledgedChanges) {
      return res.status(409).json({
        isMatch: false,
        error: 'MATERIAL_TERMS_CHANGED',
        message: 'The final contract terms differ from the explained version. Borrower re-acknowledgement required.',
        repaymentDiffPaise,
        repaymentDiffRupees: repaymentDiffPaise / 100,
        sanctionedMatches,
        upfrontMatches,
        netMatches,
        repaymentMatches
      });
    }

    res.json({
      isMatch,
      status: 'verified',
      repaymentDiffPaise,
      repaymentDiffRupees: repaymentDiffPaise / 100,
      timestamp: new Date().toISOString()
    });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// Vite middleware configuration
async function start() {
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Termly Server running on http://0.0.0.0:${PORT}`);
  });
}

start();
