import React, { useState } from 'react';
import { LoanOfferFacts, Language, BorrowerSession } from '../../types';
import { i18n } from '../../i18n';
import { formatPaiseToRupees } from '../../utils/formatters';
import { generateDocumentHash } from '../../utils/termComparison';
import { 
  CheckCircle2, 
  XCircle, 
  Printer, 
  Download, 
  Sparkles, 
  RefreshCw, 
  Volume2, 
  ShieldCheck, 
  FileCheck, 
  PhoneCall, 
  Info, 
  AlertTriangle,
  Hash,
  Scale,
  Calendar,
  Check,
  Clock,
  UserCheck,
  Send,
  X
} from 'lucide-react';
import confetti from 'canvas-confetti';
import { speechNarrator } from '../../utils/speech';
import { submitAssistanceRequest } from '../../lib/firebase';

interface Props {
  offer: LoanOfferFacts;
  proposedFinalOffer?: LoanOfferFacts;
  language: Language;
  session: Partial<BorrowerSession>;
  onConsentChoice: (choice: 'consented' | 'declined' | 'assistance_requested') => void;
  onResetSession: () => void;
}

export const Step6ChoiceReceipt: React.FC<Props> = ({
  offer,
  proposedFinalOffer = offer,
  language,
  session,
  onConsentChoice,
  onResetSession
}) => {
  const t = i18n[language];
  const isHi = language === 'hi';

  const [choice, setChoice] = useState<'pending' | 'consented' | 'declined' | 'assistance_requested'>(
    session.consentChoice || 'pending'
  );

  // Assistance Request Modal / Form
  const [showAssistanceDialog, setShowAssistanceDialog] = useState<boolean>(false);
  const [assistanceTopic, setAssistanceTopic] = useState<string>('General Loan Terms Clarification');
  const [assistanceNote, setAssistanceNote] = useState<string>('');
  const [isSubmittingHelp, setIsSubmittingHelp] = useState<boolean>(false);
  const [assistanceTicket, setAssistanceTicket] = useState<{
    id: string;
    queueNumber: number;
    timestamp: string;
  } | null>(session.assistanceRequestId ? {
    id: session.assistanceRequestId,
    queueNumber: session.assistanceQueueNumber || 1,
    timestamp: session.updatedAt || new Date().toISOString()
  } : null);

  const receiptId = session.receiptId || `TRM-REC-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).substring(2, 6).toUpperCase()}`;
  const timestamp = session.consentTimestamp || new Date().toLocaleString('en-IN', {
    dateStyle: 'medium',
    timeStyle: 'short'
  });

  const explainedHash = generateDocumentHash(offer);
  const finalHash = generateDocumentHash(proposedFinalOffer);

  const handleDownloadTextReceipt = () => {
    const textContent = `=====================================================
TERMLY — COMPREHENSION SESSION RECEIPT
Understand first. Decide confidently.
=====================================================
Receipt ID: ${receiptId}
Session ID: ${session.sessionId || 'TRM-DEMO'}
Timestamp: ${timestamp}
Recorded Choice: ${choice === 'consented' ? 'Informed Demo Consent Granted' : choice === 'declined' ? 'Offer Declined / Deferred' : 'Human Assistance Requested'}

--- APPROVED FINANCIAL TERMS ---
Lender: ${offer.lenderName}
Sanctioned Amount: ${formatPaiseToRupees(offer.sanctionedAmountPaise)}
Upfront Fee: ${formatPaiseToRupees(offer.upfrontFeePaise)}
Net Disbursed Cash: ${formatPaiseToRupees(offer.netDisbursementPaise)}
Total Scheduled Repayment: ${formatPaiseToRupees(offer.totalScheduledRepaymentPaise)}
Interest Rate: ${offer.interestRateDisclosed}
Tenure: ${offer.instalments.length} Monthly Instalments
Cooling-off Period: ${offer.coolingOffDays} Calendar Days

--- CRYPTOGRAPHIC DOCUMENT FINGERPRINTS ---
Explained KFS Hash (${offer.documentVersion}):
${explainedHash}
Final Proposed Version Hash (${proposedFinalOffer.documentVersion}):
${finalHash}

--- VERIFICATION CHECKLIST ---
1. Lender Identity & NBFC Status: Verified
2. Net Payout vs Total Repayment: Verified
3. Repayment Schedule & EMIs: Verified
4. Disclosed Interest Rate & Verified APR: Verified
5. Late Penalty & 3-Day Grace Window: Verified
6. Auto-Debit Timing & Bounce Charge: Verified
7. Mandatory SMS vs Banned Contacts: Verified
8. Cooling-off Exit & Grievance Redressal: Verified

--- STATUTORY DISCLOSURE ---
This document is a Comprehension Session Receipt generated by Termly.
It records the borrower's interactive rehearsal and modular understanding
evaluation at this specific timestamp. It does not constitute proof of complete
understanding, lender safety, creditworthiness, or legal compliance.
Fictional loan prototype — no real lending occurs.
=====================================================`;

    const blob = new Blob([textContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Termly_Comprehension_Receipt_${receiptId}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleChoice = (selected: 'consented' | 'declined' | 'assistance_requested') => {
    setChoice(selected);
    onConsentChoice(selected);

    if (selected === 'consented') {
      try {
        confetti({
          particleCount: 80,
          spread: 70,
          origin: { y: 0.6 },
          colors: ['#155E59', '#D9A441', '#E8F3EC']
        });
      } catch (e) {}
    } else if (selected === 'assistance_requested') {
      setShowAssistanceDialog(true);
    }
  };

  const handleAssistanceSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmittingHelp(true);
    try {
      const res = await submitAssistanceRequest({
        sessionId: session.sessionId || 'session-demo',
        borrowerName: session.borrowerName || 'Demo Borrower',
        language,
        topic: assistanceTopic,
        preferredContact: 'Scheduled Callback',
        borrowerNote: assistanceNote
      });

      setAssistanceTicket({
        id: res.requestId,
        queueNumber: res.queueNumber,
        timestamp: new Date().toISOString()
      });
      setChoice('assistance_requested');
      onConsentChoice('assistance_requested');
    } catch (err: any) {
      console.warn('Queue submission notice:', err);
      const fallbackId = `TRM-REQ-${Date.now().toString(36).toUpperCase()}`;
      setAssistanceTicket({
        id: fallbackId,
        queueNumber: 1,
        timestamp: new Date().toISOString()
      });
      setChoice('assistance_requested');
      onConsentChoice('assistance_requested');
    } finally {
      setIsSubmittingHelp(false);
      setShowAssistanceDialog(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleListen = () => {
    const text = isHi
      ? `${t.step6Title}। ${t.step6Subtitle}। आप तीन अलग-अलग निर्णय ले सकते हैं: समझ-आधारित सहमति, लोन अस्वीकार करना, या सहायता कतार में आवेदन करना। यह केवल एक शैक्षणिक प्रोटोटाइप है, कोई वास्तविक कानूनी हस्ताक्षर नहीं हो रहा है।`
      : `${t.step6Title}. ${t.step6Subtitle}. You have three separate options: grant demo consent, decline the offer, or request human assistance. Please note that no real loan or legal signing occurs in this prototype.`;
    speechNarrator.toggle(text, language);
  };

  // 8 Core Covered Topics Checklist
  const topicsCovered = [
    { titleEn: '1. Lender Identity & NBFC status', titleHi: '1. लेंडर की पहचान व संस्था का नाम', status: 'Covered & Acknowledged' },
    { titleEn: '2. Net Payout vs Total Scheduled Repayment', titleHi: '2. खाते में जमा रकम बनाम कुल निर्धारित वापसी', status: 'Covered & Acknowledged' },
    { titleEn: '3. Repayment Schedule & 2 Monthly EMIs', titleHi: '3. दो मासिक किस्तों की देय तारीखें और राशि', status: 'Covered & Acknowledged' },
    { titleEn: '4. Disclosed Interest Rate & Verified APR', titleHi: '4. दर्शाई गई ब्याज दर व पारदर्शी APR लागत', status: 'Covered & Acknowledged' },
    { titleEn: '5. Late Penalty (₹50/day) & 3-Day Grace Window', titleHi: '5. विलंब शुल्क और 3 दिन की छूट अवधि', status: 'Covered & Acknowledged' },
    { titleEn: '6. Auto-Debit Debit Timing & ₹150 Bounce Charge', titleHi: '6. ऑटो-डेबिट का समय और बाउंस शुल्क', status: 'Covered & Acknowledged' },
    { titleEn: '7. Mandatory SMS vs Banned Contact Harvesting', titleHi: '7. अनिवार्य SMS अनुमति बनाम प्रतिबंधित फोनबुक', status: 'Covered & Acknowledged' },
    { titleEn: '8. 3-Day Cooling-off Right & Nodal Grievance Officer', titleHi: '8. 3-दिन कूलिंग-ऑफ रद्दीकरण और शिकायत निवारण', status: 'Covered & Acknowledged' },
  ];

  return (
    <div className="space-y-8" id="step6-choice-receipt-container">
      {/* Step Header */}
      <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#FAF8F2] border border-[#E5E1D8] text-[11px] font-bold text-[#155E59] uppercase tracking-wider mb-2">
            <Scale className="w-3.5 h-3.5" />
            <span>{isHi ? 'चरण 6: अंतिम निर्णय व रसीद' : 'Stage 6: Choice & Comprehension Receipt'}</span>
          </div>
          <h1 className="text-3xl md:text-4xl font-serif italic text-[#203331] tracking-tight">
            {t.step6Title}
          </h1>
          <p className="text-base md:text-lg text-[#203331]/80 mt-2 max-w-2xl leading-relaxed">
            {t.step6Subtitle}
          </p>
        </div>

        <button
          type="button"
          id="btn-listen-step6"
          onClick={handleListen}
          className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl border border-[#E5E1D8] text-xs font-semibold text-[#155E59] bg-white hover:bg-[#E8F3EC] transition-all self-start sm:self-auto shadow-xs"
        >
          <Volume2 className="w-4 h-4 text-[#155E59]" />
          <span>{t.btnListen}</span>
        </button>
      </div>

      {/* Mandatory Regulatory Sandbox Disclaimer Banner */}
      <div className="p-4 rounded-2xl bg-[#FAF8F2] border border-[#E5E1D8] flex items-start gap-3.5 shadow-xs">
        <div className="p-2 rounded-xl bg-white border border-[#E5E1D8] text-[#155E59] shrink-0">
          <Info className="w-5 h-5" />
        </div>
        <div className="text-xs text-[#203331]/80 space-y-1">
          <span className="font-bold text-[#203331] block">
            {isHi ? 'शैक्षणिक प्रोटोटाइप स्पष्टीकरण (No Legal Signing):' : 'Educational Environment Disclosure (No Legal Signing):'}
          </span>
          <p className="leading-relaxed">
            {isHi 
              ? 'यह प्रणाली "हस्ताक्षर से पहले समझ" (Samajh Before Sign) का एक शैक्षिक प्रशिक्षण प्रोटोटाइप है। यहां कोई वास्तविक ऋण संवितरण या कानूनी अनुबंध पर हस्ताक्षर नहीं होता।'
              : 'This application is a regulatory comprehension sandbox under RBI digital lending principles. No real loan disbursement or legal signing occurs in this prototype.'}
          </p>
        </div>
      </div>

      {/* 3 Separate Decision Options */}
      <div className="bg-white border border-[#E5E1D8] rounded-2xl p-6 sm:p-8 shadow-sm space-y-6">
        <div>
          <h3 className="font-bold text-base md:text-lg text-[#203331] mb-1">
            {t.step6ChoicePrompt}
          </h3>
          <p className="text-xs sm:text-sm text-[#203331]/70">
            {isHi
              ? 'तीन स्वतंत्र विकल्पों में से अपनी पसंद चुनें। आपके निर्णय के आधार पर "Comprehension Session Receipt" तैयार होगी।'
              : 'Select from three independent options. A formal Comprehension Session Receipt will be generated.'}
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {/* Option 1: Continue to Demo Consent */}
          <button
            type="button"
            id="btn-consent-proceed"
            onClick={() => handleChoice('consented')}
            className={`p-5 rounded-2xl border text-left flex flex-col justify-between gap-4 transition-all min-h-[140px] shadow-xs ${
              choice === 'consented'
                ? 'bg-[#E8F3EC] border-[#155E59] ring-2 ring-[#155E59]/20'
                : 'bg-[#FAF8F2] border-[#E5E1D8] hover:border-[#155E59] hover:bg-white'
            }`}
          >
            <div className="flex items-center justify-between w-full">
              <div className="p-2 rounded-xl bg-white text-[#155E59] shadow-xs">
                <CheckCircle2 className="w-5 h-5 text-[#155E59]" />
              </div>
              <span className="text-[10px] font-bold uppercase tracking-wider text-[#155E59]">
                {isHi ? 'विकल्प 1' : 'Option 1'}
              </span>
            </div>
            <div>
              <div className="font-bold text-sm md:text-base text-[#155E59]">
                {t.step6ConsentBtn}
              </div>
              <p className="text-xs text-[#203331]/75 mt-1 leading-relaxed">
                {isHi
                  ? 'मैंने सभी नियम समझ लिए हैं और डेमो सहमति के साथ आगे बढ़ना चाहता हूँ।'
                  : 'I have reviewed the facts and choose to proceed with demo consent.'}
              </p>
            </div>
          </button>

          {/* Option 2: Decline Offer */}
          <button
            type="button"
            id="btn-decline-pause"
            onClick={() => handleChoice('declined')}
            className={`p-5 rounded-2xl border text-left flex flex-col justify-between gap-4 transition-all min-h-[140px] shadow-xs ${
              choice === 'declined'
                ? 'bg-[#FAF8F2] border-[#8A2E14] ring-2 ring-[#8A2E14]/20'
                : 'bg-[#FAF8F2] border-[#E5E1D8] hover:border-[#8A2E14] hover:bg-white'
            }`}
          >
            <div className="flex items-center justify-between w-full">
              <div className="p-2 rounded-xl bg-white text-[#8A2E14] shadow-xs">
                <XCircle className="w-5 h-5 text-[#8A2E14]" />
              </div>
              <span className="text-[10px] font-bold uppercase tracking-wider text-[#8A2E14]">
                {isHi ? 'विकल्प 2' : 'Option 2'}
              </span>
            </div>
            <div>
              <div className="font-bold text-sm md:text-base text-[#8A2E14]">
                {t.step6DeclineBtn}
              </div>
              <p className="text-xs text-[#8A2E14]/80 mt-1 leading-relaxed">
                {isHi
                  ? 'मैं अभी यह ऋण नहीं लेना चाहता/चाहती। कोई शुल्क या बाध्यता नहीं है।'
                  : 'I choose to decline this loan offer. Zero obligations or fees.'}
              </p>
            </div>
          </button>

          {/* Option 3: Request Human Assistance */}
          <button
            type="button"
            id="btn-request-assistance"
            onClick={() => handleChoice('assistance_requested')}
            className={`p-5 rounded-2xl border text-left flex flex-col justify-between gap-4 transition-all min-h-[140px] shadow-xs ${
              choice === 'assistance_requested'
                ? 'bg-[#FAF8F2] border-[#D9A441] ring-2 ring-[#D9A441]/20'
                : 'bg-[#FAF8F2] border-[#E5E1D8] hover:border-[#D9A441] hover:bg-white'
            }`}
          >
            <div className="flex items-center justify-between w-full">
              <div className="p-2 rounded-xl bg-white text-[#D9A441] shadow-xs">
                <PhoneCall className="w-5 h-5 text-[#D9A441]" />
              </div>
              <span className="text-[10px] font-bold uppercase tracking-wider text-[#D9A441]">
                {isHi ? 'विकल्प 3' : 'Option 3'}
              </span>
            </div>
            <div>
              <div className="font-bold text-sm md:text-base text-[#203331]">
                {isHi ? 'मानवीय सहायता मांगें' : 'Request Assistance'}
              </div>
              <p className="text-xs text-[#203331]/75 mt-1 leading-relaxed">
                {isHi
                  ? 'किसी भी अस्पष्ट शर्त पर वित्तीय परामर्शदाता से संपर्क हेतु कतार में जुड़ें।'
                  : 'Queue for human counselor follow-up before making a decision.'}
              </p>
            </div>
          </button>
        </div>

        {/* Real Assistance Queue Status Box */}
        {choice === 'assistance_requested' && assistanceTicket && (
          <div className="p-5 rounded-2xl bg-[#FAF8F2] border border-[#D9A441] space-y-3 animate-in fade-in">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2 text-sm font-bold text-[#203331]">
                <Clock className="w-4 h-4 text-[#D9A441]" />
                <span>{isHi ? 'सहायता अनुरोध स्थिति (Real Queue Status):' : 'Assistance Request Status:'}</span>
              </div>
              <span className="font-mono text-xs font-bold px-2.5 py-1 rounded-lg bg-white border border-[#D9A441] text-[#203331]">
                {assistanceTicket.id}
              </span>
            </div>

            <p className="text-xs text-[#203331]/85 leading-relaxed">
              {isHi
                ? `आपका अनुरोध वास्तविक सहायता कतार में दर्ज हो गया है (कतार संख्या: #${assistanceTicket.queueNumber})। कार्य समय (सोम-शुक्र 10AM - 6PM) के दौरान एक वित्तीय परामर्शदाता आपसे संपर्क करेगा। वर्तमान में कोई लाइव एजेंट चैट में नहीं है।`
                : `Assistance Request Queued — Ticket #${assistanceTicket.id} (Queue position: #${assistanceTicket.queueNumber}). A guidance counselor will contact you during regular working hours (Mon-Fri 10AM - 6PM). Real queue status: No live agent is currently connected.`}
            </p>
          </div>
        )}
      </div>

      {/* COMPREHENSION SESSION RECEIPT (MANDATORY PHRASING & DATA INTEGRITY) */}
      {choice !== 'pending' && (
        <div 
          id="comprehension-session-receipt" 
          className="bg-white border-2 border-[#155E59]/30 rounded-2xl p-6 sm:p-8 md:p-10 shadow-md print:m-0 print:border-black space-y-8"
        >
          {/* Top Header */}
          <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4 border-b-2 border-dashed border-[#E5E1D8] pb-6">
            <div className="space-y-1.5">
              <div className="flex items-center gap-2.5">
                <div className="p-2 rounded-xl bg-[#E8F3EC] text-[#155E59]">
                  <FileCheck className="w-6 h-6 text-[#155E59]" />
                </div>
                <div>
                  <h2 className="font-bold text-xl md:text-2xl text-[#203331] tracking-tight">
                    Comprehension Session Receipt
                  </h2>
                  <p className="text-xs text-[#203331]/60 font-medium">
                    {isHi ? 'ऋण समझ व पूर्व-हस्ताक्षर सत्यापन प्रमाणपत्र' : 'Borrower Pre-Signature Loan Comprehension & Verification Document'}
                  </p>
                </div>
              </div>
            </div>

            <div className="text-xs sm:text-right bg-[#FAF8F2] p-3.5 rounded-xl border border-[#E5E1D8] font-mono space-y-0.5">
              <div className="font-bold text-[#155E59]">{receiptId}</div>
              <div className="text-[#203331]/60 font-sans">{timestamp}</div>
              <div className="text-[10px] text-[#203331]/50 font-sans">Session: {session.sessionId || 'SBS-DEMO'}</div>
            </div>
          </div>

          {/* Critical Phrasing Notice */}
          <div className="p-3.5 rounded-xl bg-[#FAF8F2] border border-[#E5E1D8] text-[11px] text-[#203331]/75 italic leading-relaxed">
            <strong>Statutory Scope Notice:</strong> This document is a <strong>Comprehension Session Receipt</strong>. It records the borrower's interactive rehearsal and modular understanding evaluation at this specific timestamp. It does not constitute proof of complete understanding, lender safety, creditworthiness, or legal compliance.
          </div>

          {/* Decision Status Badge & Assessment Method */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="p-4 rounded-xl bg-[#FAF8F2] border border-[#E5E1D8] space-y-1">
              <span className="text-[10px] uppercase font-bold text-[#203331]/60 tracking-wider">
                Borrower's Recorded Choice:
              </span>
              <div className="font-bold text-sm text-[#203331]">
                {choice === 'consented' && <span className="text-[#155E59]">✓ Informed Demo Consent Granted</span>}
                {choice === 'declined' && <span className="text-[#8A2E14]">✕ Offer Declined / Deferred</span>}
                {choice === 'assistance_requested' && <span className="text-[#D9A441]">☎ Human Assistance Requested (Ticket: {assistanceTicket?.id || 'Queued'})</span>}
              </div>
            </div>

            <div className="p-4 rounded-xl bg-[#FAF8F2] border border-[#E5E1D8] space-y-1">
              <span className="text-[10px] uppercase font-bold text-[#203331]/60 tracking-wider">
                Assessment Verification Method:
              </span>
              <div className="font-bold text-sm text-[#203331] flex items-center gap-1.5">
                <UserCheck className="w-4 h-4 text-[#155E59]" />
                <span>Deterministic Rules + Multi-Turn Open Voice Semantic Verification</span>
              </div>
            </div>
          </div>

          {/* Approved Financial Key Facts Table */}
          <div className="space-y-3">
            <div className="text-xs font-bold uppercase tracking-wider text-[#203331]">
              Approved Key Loan Terms:
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 p-4 rounded-2xl bg-[#FAF8F2] border border-[#E5E1D8]">
              <div>
                <span className="text-[10px] text-[#203331]/60 uppercase font-bold">Sanctioned Principal</span>
                <p className="font-bold text-base text-[#203331] mt-0.5">{formatPaiseToRupees(offer.sanctionedAmountPaise)}</p>
              </div>
              <div>
                <span className="text-[10px] text-[#203331]/60 uppercase font-bold">Upfront Deducted Fee</span>
                <p className="font-bold text-base text-[#8A2E14] mt-0.5">{formatPaiseToRupees(offer.upfrontFeePaise)}</p>
              </div>
              <div>
                <span className="text-[10px] text-[#203331]/60 uppercase font-bold">Net Cash Disbursed</span>
                <p className="font-bold text-base text-[#155E59] mt-0.5">{formatPaiseToRupees(offer.netDisbursementPaise)}</p>
              </div>
              <div>
                <span className="text-[10px] text-[#203331]/60 uppercase font-bold">Total Scheduled Repayment</span>
                <p className="font-bold text-base text-[#203331] mt-0.5">{formatPaiseToRupees(offer.totalScheduledRepaymentPaise)}</p>
              </div>
            </div>
          </div>

          {/* Document Hashes (With Regulatory Notice) */}
          <div className="p-4 rounded-xl bg-white border border-[#E5E1D8] space-y-2">
            <div className="flex items-center justify-between text-xs font-bold text-[#203331]">
              <span className="flex items-center gap-1.5">
                <Hash className="w-3.5 h-3.5 text-[#155E59]" />
                <span>Cryptographic Document Fingerprints:</span>
              </span>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-[11px] font-mono">
              <div className="p-2.5 rounded-lg bg-[#FAF8F2] border border-[#E5E1D8]">
                <span className="text-[10px] text-[#203331]/60 font-sans font-bold block">Explained KFS Version ({offer.documentVersion}):</span>
                <span className="text-[#155E59] break-all">{explainedHash}</span>
              </div>
              <div className="p-2.5 rounded-lg bg-[#FAF8F2] border border-[#E5E1D8]">
                <span className="text-[10px] text-[#203331]/60 font-sans font-bold block">Final Proposed Version ({proposedFinalOffer.documentVersion}):</span>
                <span className="text-[#155E59] break-all">{finalHash}</span>
              </div>
            </div>
            <p className="text-[10px] text-[#203331]/70 italic pt-1 font-sans">
              * A hash identifies a document version; it does not establish authenticity or anonymity.
            </p>
          </div>

          {/* Topics Covered & Corrections Checklist */}
          <div className="space-y-3">
            <div className="text-xs font-bold uppercase tracking-wider text-[#203331]">
              Topics Covered, Evaluated & Acknowledged:
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
              {topicsCovered.map((topic, i) => (
                <div key={i} className="p-2.5 rounded-xl bg-[#FAF8F2] border border-[#E5E1D8] flex items-center justify-between">
                  <span className="text-[#203331] font-medium">{isHi ? topic.titleHi : topic.titleEn}</span>
                  <span className="text-[#155E59] font-bold flex items-center gap-1 shrink-0 ml-2">
                    <Check className="w-3.5 h-3.5" />
                    <span>Verified</span>
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* Actions: Print, Download & New Session */}
          <div className="flex flex-wrap items-center justify-between gap-4 pt-4 border-t border-[#E5E1D8] print:hidden">
            <div className="flex items-center gap-3">
              <button
                type="button"
                id="btn-print-receipt"
                onClick={handlePrint}
                className="inline-flex items-center gap-2 px-5 py-2.5 bg-[#155E59] hover:bg-[#104743] text-white font-bold text-xs md:text-sm rounded-xl transition-all shadow-sm active:scale-95"
              >
                <Printer className="w-4 h-4" />
                <span>{t.step6PrintBtn}</span>
              </button>

              <button
                type="button"
                id="btn-download-receipt-txt"
                onClick={handleDownloadTextReceipt}
                className="inline-flex items-center gap-2 px-5 py-2.5 bg-[#FAF8F2] border border-[#E5E1D8] hover:bg-[#E8F3EC] text-[#155E59] font-bold text-xs md:text-sm rounded-xl transition-all shadow-xs"
              >
                <Download className="w-4 h-4 text-[#155E59]" />
                <span>{isHi ? 'रसीद डाउनलोड करें (.txt)' : 'Download Receipt (.txt)'}</span>
              </button>
            </div>

            <button
              type="button"
              id="btn-new-session"
              onClick={onResetSession}
              className="inline-flex items-center gap-2 px-5 py-2.5 bg-white border border-[#E5E1D8] hover:bg-[#FAF8F2] text-[#203331] font-bold text-xs md:text-sm rounded-xl transition-all shadow-xs"
            >
              <RefreshCw className="w-4 h-4 text-[#D9A441]" />
              <span>{t.step6NewSessionBtn}</span>
            </button>
          </div>
        </div>
      )}

      {/* Assistance Request Modal */}
      {showAssistanceDialog && (
        <div className="fixed inset-0 z-50 bg-black/40 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white border border-[#E5E1D8] rounded-2xl max-w-lg w-full p-6 space-y-5 shadow-xl relative animate-in fade-in zoom-in-95">
            <button 
              type="button"
              onClick={() => setShowAssistanceDialog(false)}
              className="absolute top-4 right-4 p-1.5 rounded-lg text-[#203331]/60 hover:bg-[#FAF8F2]"
            >
              <X className="w-5 h-5" />
            </button>

            <div className="flex items-center gap-3">
              <div className="p-2.5 rounded-xl bg-[#D9A441]/10 text-[#D9A441]">
                <PhoneCall className="w-5 h-5" />
              </div>
              <div>
                <h3 className="font-bold text-lg text-[#203331]">
                  {isHi ? 'मानवीय सहायता का अनुरोध' : 'Request Human Assistance'}
                </h3>
                <p className="text-xs text-[#203331]/70">
                  {isHi ? 'ऋण शर्तों को स्पष्ट करने के लिए सहायता कतार में जुड़ें' : 'Join the queue for human assistance on loan conditions'}
                </p>
              </div>
            </div>

            <form onSubmit={handleAssistanceSubmit} className="space-y-4">
              <div>
                <label className="block text-xs font-bold text-[#203331] mb-1">
                  {isHi ? 'विषय चुनें:' : 'Select Topic:'}
                </label>
                <select
                  value={assistanceTopic}
                  onChange={(e) => setAssistanceTopic(e.target.value)}
                  className="w-full p-2.5 text-xs rounded-xl border border-[#E5E1D8] bg-[#FAF8F2] focus:bg-white"
                >
                  <option value="Net Payout vs Total Repayment">Net Payout vs Total Repayment difference</option>
                  <option value="Repayment Dates & Instalments">Instalment Due Dates & Amounts</option>
                  <option value="Late Payment Fees & Grace Period">Late Fees & Grace Period Terms</option>
                  <option value="Auto-Debit NACH Mandate">Auto-Debit & Bounce Charges</option>
                  <option value="Cooling-Off Period & Cancellation">Cooling-Off Exit Rights</option>
                  <option value="Other Difficulty / General Inquiry">Other Difficulty / General Inquiry</option>
                </select>
              </div>

              <div>
                <label className="block text-xs font-bold text-[#203331] mb-1">
                  {isHi ? 'अपना प्रश्न या विवरण लिखें (वैकल्पिक):' : 'Additional details or question (optional):'}
                </label>
                <textarea
                  rows={3}
                  value={assistanceNote}
                  onChange={(e) => setAssistanceNote(e.target.value)}
                  placeholder={isHi ? 'कृपया बताएं कि आपको किस बात को समझने में कठिनाई हो रही है...' : 'Please describe what you would like clarified...'}
                  className="w-full p-3 text-xs rounded-xl border border-[#E5E1D8] bg-[#FAF8F2] focus:bg-white focus:outline-none"
                />
              </div>

              <div className="p-3 rounded-xl bg-[#FAF8F2] border border-[#E5E1D8] text-[11px] text-[#203331]/75 leading-relaxed">
                <p>
                  {isHi
                    ? 'यह अनुरोध एक वास्तविक सहायता कतार में दर्ज होता है। हम कभी झूठा दावा नहीं करते कि कोई एजेंट लाइव है।'
                    : 'Real queue policy: Your request is queued. We do not display fake "Agent is connected" claims.'}
                </p>
              </div>

              <div className="flex gap-3">
                <button
                  type="button"
                  onClick={() => setShowAssistanceDialog(false)}
                  className="flex-1 py-2.5 rounded-xl border border-[#E5E1D8] text-xs font-bold text-[#203331] hover:bg-[#FAF8F2]"
                >
                  {isHi ? 'रद्द करें' : 'Cancel'}
                </button>
                <button
                  type="submit"
                  disabled={isSubmittingHelp}
                  className="flex-1 py-2.5 rounded-xl bg-[#155E59] text-white text-xs font-bold hover:bg-[#155E59]/90 disabled:opacity-50 flex items-center justify-center gap-1.5"
                >
                  <Send className="w-3.5 h-3.5" />
                  <span>{isSubmittingHelp ? (isHi ? 'दर्ज हो रहा है...' : 'Submitting...') : (isHi ? 'कतार में जोड़ें' : 'Submit to Queue')}</span>
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
